### ISSUE TITLE
woah rude

### ISSUE THREAD

**Issue by emilyst** [tpope/gem-shut-the-fuck-up#1]
turbo rude

**Comment by tpope** [comment]
cantfix wontfix

**Comment by rosenfeld** [comment]
@tpope, congrats for the initiative.

It would be better if could silent specific gems only, like `httparty` since some others may have useful changelogs that we could be interested on during a `bundle update` for example... Maybe we could have a ~/.silenced_gems file where we could just put "httparty" there. Maybe installing `gem-shut-the-fuck-up` could create this file with this line by default...

**Comment by manuelmeurer** [comment]
This would actually be a nice gem that people used if you hadn't decided to include random and unnecessary cursing. But hey, to each his own. :smile:

**Comment by Frexuz** [comment]
_**Brilliant**_
